### ISSUE TITLE
Add 'How to Contribute` type category

### ISSUE THREAD

**Issue by sheriffderek** [ember-community-russia/awesome-ember#40]
There's been a few great articles about where to start / and different areas and ways of contributing:

part-1 https://www.kennethlarsen.org/how-to-contribute-to-the-ember-times/

part-2 https://www.kennethlarsen.org/how-to-contribute-ember-release-post  

- it would be great to have an area for those.

**Comment by lifeart** [comment]
@sheriffderek  thank you! Added https://github.com/ember-community-russia/awesome-ember/blob/master/README.md#contribution-guides
