### ISSUE TITLE
Preparing for the global awesome list

### ISSUE THREAD

**Issue by DenisNazarenko** [ember-community-russia/awesome-ember#48]
Fixes for PR [#1579](https://github.com/sindresorhus/awesome/pull/1579)

- [x]  Dead urls.
- [x] Includes a succinct description of the project/theme at the top of the readme.
- [ ] `contributing.md` should be customized for current list.
- [x] The repo description needs to be improved.
- [x] Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
- [x] The item descriptions should not be in title case.
- [x] Item descriptions needs to be improved. Typos should be fixed.

**Comment by DenisNazarenko** [comment]
Regarding this [comment](https://github.com/sindresorhus/awesome/pull/1579#issuecomment-516987873):
- link `https://github.com/freshbooks/ember-responsive` is not dead 
- link `https://github.com/twokul/ember-cli-pact` was removed ==> https://github.com/ember-community-russia/awesome-ember/pull/49/commits/43e33ea25e0e5fff3514373ffa49d55833a76a0d

**Comment by lifeart** [comment]
Closing it, because now we in awesome list, thank you @DenisNazarenko!
